# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_address_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered_time',
        ),
        migrations.AddField(
            model_name='order',
            name='tries_number',
            field=models.IntegerField(default=0),
        ),
    ]
