# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171105_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_day', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dv', to='core.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='driver',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='core.Delivery'),
        ),
    ]
