# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171105_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_setted',
            field=models.BooleanField(default=False),
        ),
    ]
