# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171105_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='forecast_day',
            field=models.DateField(null=True),
        ),
    ]
