# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20171105_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='distance_from_last',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_from_last',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
