# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171105_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_setted',
            field=models.BooleanField(default=False),
        ),
    ]
