# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20171106_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_message',
            field=models.CharField(default='{"date":"null","message":"null","icon":"null","title":"null"}', max_length=180),
        ),
    ]
