# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20171106_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_message',
            field=models.CharField(max_length=180),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_warehouse', to='core.Profile'),
        ),
    ]
